#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Student
#        - App\Entity\Resource

# javiereguiluz/easyadmin-bundle
easy_admin:
    entities:
        Student:
            class: AppBundle\Entity\Student
            list:
                fields: ['firtname', 'lastname','response']
            form:
                fields:
                    - 'firstname'
                    - 'lastname'
                    - 'response'
        Resource:
            class: AppBundle\Entity\Resource
            list:
                fields: ['soft', 'alcohol', 'food', { property: 'student.firstname', label: 'Category' }]
            form:
                fields:
                    - 'soft'
                    - 'alcohol'
                    - 'food'
                    - { property: 'students', type: 'entity', type_options: { choice_label: 'firstname', multiple: true }}
